### ISSUE TITLE
GET Error

### ISSUE THREAD

**Issue by chadsfatherlali** [strongloop/generator-loopback#244]
Hi, I try to deploy simple api example from strongloop and I get this error:

[root@localhost simple-api]# sudo npm install -g generator-loopback@latest
/usr/lib
└── generator-loopback@1.24.5 

[root@localhost simple-api]# node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
Error no gestionado para la solicitud GET /simple-api: Error: Cannot GET /simple-api
    at raiseUrlNotFoundError (/opt/bitnami/apps/simple-api/node_modules/loopback/server/middleware/url-not-found.js:20:17)
    at Layer.handle [as handle_request] (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:312:13)
    at /opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:271:10)
    at /opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:618:15
    at next (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:176:3)
    at router (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:312:13)
    at /opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/bitnami/apps/simple-api/node_modules/express/lib/router/index.js:271:10)
    at nosniff (/opt/bitnami/apps/simple-api/node_modules/dont-sniff-mimetype/index.js:4:5)

**Comment by chadsfatherlali** [comment]
A mistake on nginx configuration 😂, sorry.
