### ISSUE TITLE
export-api-def fails with path not a string error

### ISSUE THREAD

**Issue by qpresley** [strongloop/generator-loopback#276]
# Description/Steps to reproduce
Steps to reproduce are very simple.  Create a loopback app using the `lb` CLI, chose the empty server app.  When it completes run `lb export-api-def -o ./testApp.yaml` and you will get the error.  Here is the output of my local run

```
The API Connect team at IBM happily continues to develop,
support and maintain LoopBack, which is at the core of
API Connect. When your APIs need robust management and
security options, please check out http://ibm.biz/tryAPIC

Quentins-MBP:testApp qpresley$ lb export-api-def -o ./testApp.yaml
FILEPATH:  true
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at module.exports.yeoman.Base.extend.generate (/Users/qpresley/.nvm/versions/node/v4.7.2/lib/node_modules/loopback-cli/node_modules/generator-loopback/export-api-def/index.js:45:10)
    at Object.<anonymous> (/Users/qpresley/.nvm/versions/node/v4.7.2/lib/node_modules/loopback-cli/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:431:23)
    at /Users/qpresley/.nvm/versions/node/v4.7.2/lib/node_modules/loopback-cli/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /Users/qpresley/.nvm/versions/node/v4.7.2/lib/node_modules/loopback-cli/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /Users/qpresley/.nvm/versions/node/v4.7.2/lib/node_modules/loopback-cli/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

**Comment by jannyHou** [comment]
Moved to https://github.com/strongloop/loopback-cli/issues/27
