### ISSUE TITLE
lb model don't work

### ISSUE THREAD

**Issue by rzorgani** [strongloop/generator-loopback#409]
# Description/Steps to reproduce
lb -v
3.0.0 (generator-loopback@4.0.1 loopback-workspace@3.44.2)
node -v
v10.15.3
npm -v 
6.9.0
I create my project from long time (more than one year), I'm trying to add some feature, so I decide to add new model.
D:\api-project>lb model
? Entrer le nom du modèle : car 

# Link to reproduction sandbox

# Expected result
model will be created correctly

actual results nothing visible after this line (no error in the console)
? Entrer le nom du modèle : car 

# Additional information

**Comment by dhmlau** [comment]
@rzorgani, I wasn't able to reproduce it using the latest versions of the modules.  Could you please update to the most recent versions? 

I'm using `loopback-cli@5.0.2` and in the LB app, I have the following in package.json:
```
 "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^3.10.0",
    "loopback-boot": "^2.6.5",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^3.0.0",
    "loopback-component-explorer": "^6.2.0",
    "loopback": "^3.22.0"
```

**Comment by rzorgani** [comment]
@dhmlau , Thanks for your quick reply,
this is my current configuration:
```{
  "name": "api-project",
  "version": "1.0.0",
  "main": "server/server.js",
  "engines": {
    "node": ">=4"
  },
  "scripts": {
    "lint": "eslint .",
    "start": "node .",
    "posttest": "npm run lint && nsp check"
  },
  "dependencies": {
    "busboy-body-parser": "^0.3.2",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "gridfs": "^1.0.0",
    "helmet": "^1.3.0",
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^5.0.0",
    "loopback-connector-mongodb": "^1.18.1",
    "morgan": "^1.9.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^2.0.0"
  },
  "devDependencies": {
    "eslint": "^3.17.1",
    "eslint-config-loopback": "^8.0.0",
    "nsp": "^2.1.0"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "license": "UNLICENSED",
  "description": "api-project"
}
```

**Comment by dhmlau** [comment]
@rzorgani , thanks. Do you think you could update to use `loopback-cli@5.0.2`?

**Comment by rzorgani** [comment]
I have this error when I install npm i -g loopback-cli@5.0.2
```
C:\Users\user1\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\strong-ursa>if not defined npm_config_node_gyp (node "C:\Users\user1\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user1\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Les projets sont générés individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  ursaNative.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1181: impossible d'ouvrir le fichier en entrÚe 'C:\OpenSSL-Win64\lib\libeay32.lib'
[C:\Users\user1\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\strong-ursa\build\ursaNative
.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user1\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user1\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user1\AppData\Roaming\npm\node_modules\loopback-cli\node_modules\strong-ursa
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by dhmlau** [comment]
@rzorgani, it seems like this issue is similar to what's described in https://github.com/strongloop/loopback-cli/issues/69. You might want to take a look. Thanks.

**Comment by dhmlau** [comment]
@rzorgani , we've removed the dependency on ursa in the `strong-soap` repo, and believe your problem will be fixed after updating to the latest version of `loopback-cli`.  Thanks.
