### ISSUE TITLE
[slc loopback:model] There is a memory leak when adding more than 10 properties in a row

### ISSUE THREAD

**Issue by lius** [strongloop/generator-loopback#99]
```javascript
invoke   loopback:property
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:236:17)
    at run (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:445:21)
    at invoke (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/lib/actions/invoke.js:38:20)
    at null.<anonymous> (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/model/index.js:176:12)
    at null.<anonymous> (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/lib/base.js:221:7)
    at PromptUI.onCompletion (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1977:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)
    at AnonymousObserver.tryCatcher (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.completed (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:5032:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/lius/.nvm/versions/io.js/v1.6.2/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/inquirer/node_modules/rx/dist/rx.js:1914:14)

```

**Comment by bajtos** [comment]
Thank you for reporting the issue. What's your version of Node, generator-loopback, loopback-workspace and yo?

**Comment by lius** [comment]
io.js 1.6.2
generator-loopback 1.9.0 (from strongloop dependency)
loopback-workspace 3.10.0 (from generator-loopback dependency)
yeoman-generator 0.18.10 (from generator-loopback dependency)
